import Foundation
import HealthKit

// Generated by scripts/generate-healthkit-registry.mjs.
// Source refresh timestamp: 2026-04-10T06:53:51.367Z
enum GeneratedHealthKitCatalog {
    static let generatedAt = "2026-04-10T06:53:51.367Z"

    static var quantityEntries: [GeneratedHealthKitCatalogEntry<HKQuantityTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKQuantityTypeIdentifier>] = [
        .init(symbol: "stepCount", displayName: "Step Count", identifier: .stepCount),
        .init(symbol: "distanceWalkingRunning", displayName: "Distance Walking Running", identifier: .distanceWalkingRunning),
        .init(symbol: "runningGroundContactTime", displayName: "Running Ground Contact Time", identifier: .runningGroundContactTime),
        .init(symbol: "runningPower", displayName: "Running Power", identifier: .runningPower),
        .init(symbol: "runningSpeed", displayName: "Running Speed", identifier: .runningSpeed),
        .init(symbol: "runningStrideLength", displayName: "Running Stride Length", identifier: .runningStrideLength),
        .init(symbol: "runningVerticalOscillation", displayName: "Running Vertical Oscillation", identifier: .runningVerticalOscillation),
        .init(symbol: "distanceCycling", displayName: "Distance Cycling", identifier: .distanceCycling),
        .init(symbol: "pushCount", displayName: "Push Count", identifier: .pushCount),
        .init(symbol: "distanceWheelchair", displayName: "Distance Wheelchair", identifier: .distanceWheelchair),
        .init(symbol: "swimmingStrokeCount", displayName: "Swimming Stroke Count", identifier: .swimmingStrokeCount),
        .init(symbol: "distanceSwimming", displayName: "Distance Swimming", identifier: .distanceSwimming),
        .init(symbol: "distanceDownhillSnowSports", displayName: "Distance Downhill Snow Sports", identifier: .distanceDownhillSnowSports),
        .init(symbol: "basalEnergyBurned", displayName: "Basal Energy Burned", identifier: .basalEnergyBurned),
        .init(symbol: "activeEnergyBurned", displayName: "Active Energy Burned", identifier: .activeEnergyBurned),
        .init(symbol: "flightsClimbed", displayName: "Flights Climbed", identifier: .flightsClimbed),
        .init(symbol: "nikeFuel", displayName: "Nike Fuel", identifier: .nikeFuel),
        .init(symbol: "appleExerciseTime", displayName: "Apple Exercise Time", identifier: .appleExerciseTime),
        .init(symbol: "appleMoveTime", displayName: "Apple Move Time", identifier: .appleMoveTime),
        .init(symbol: "appleStandTime", displayName: "Apple Stand Time", identifier: .appleStandTime),
        .init(symbol: "vo2Max", displayName: "VO2 Max", identifier: .vo2Max),
        .init(symbol: "crossCountrySkiingSpeed", displayName: "Cross Country Skiing Speed", identifier: .crossCountrySkiingSpeed),
        .init(symbol: "cyclingCadence", displayName: "Cycling Cadence", identifier: .cyclingCadence),
        .init(symbol: "cyclingFunctionalThresholdPower", displayName: "Cycling Functional Threshold Power", identifier: .cyclingFunctionalThresholdPower),
        .init(symbol: "cyclingPower", displayName: "Cycling Power", identifier: .cyclingPower),
        .init(symbol: "cyclingSpeed", displayName: "Cycling Speed", identifier: .cyclingSpeed),
        .init(symbol: "distanceCrossCountrySkiing", displayName: "Distance Cross Country Skiing", identifier: .distanceCrossCountrySkiing),
        .init(symbol: "distancePaddleSports", displayName: "Distance Paddle Sports", identifier: .distancePaddleSports),
        .init(symbol: "distanceRowing", displayName: "Distance Rowing", identifier: .distanceRowing),
        .init(symbol: "distanceSkatingSports", displayName: "Distance Skating Sports", identifier: .distanceSkatingSports),
        .init(symbol: "estimatedWorkoutEffortScore", displayName: "Estimated Workout Effort Score", identifier: .estimatedWorkoutEffortScore),
        .init(symbol: "paddleSportsSpeed", displayName: "Paddle Sports Speed", identifier: .paddleSportsSpeed),
        .init(symbol: "physicalEffort", displayName: "Physical Effort", identifier: .physicalEffort),
        .init(symbol: "rowingSpeed", displayName: "Rowing Speed", identifier: .rowingSpeed),
        .init(symbol: "workoutEffortScore", displayName: "Workout Effort Score", identifier: .workoutEffortScore),
        .init(symbol: "height", displayName: "Height", identifier: .height),
        .init(symbol: "bodyMass", displayName: "Body Mass", identifier: .bodyMass),
        .init(symbol: "bodyMassIndex", displayName: "Body Mass Index", identifier: .bodyMassIndex),
        .init(symbol: "leanBodyMass", displayName: "Lean Body Mass", identifier: .leanBodyMass),
        .init(symbol: "bodyFatPercentage", displayName: "Body Fat Percentage", identifier: .bodyFatPercentage),
        .init(symbol: "waistCircumference", displayName: "Waist Circumference", identifier: .waistCircumference),
        .init(symbol: "appleSleepingWristTemperature", displayName: "Apple Sleeping Wrist Temperature", identifier: .appleSleepingWristTemperature),
        .init(symbol: "basalBodyTemperature", displayName: "Basal Body Temperature", identifier: .basalBodyTemperature),
        .init(symbol: "environmentalAudioExposure", displayName: "Environmental Audio Exposure", identifier: .environmentalAudioExposure),
        .init(symbol: "environmentalSoundReduction", displayName: "Environmental Sound Reduction", identifier: .environmentalSoundReduction),
        .init(symbol: "headphoneAudioExposure", displayName: "Headphone Audio Exposure", identifier: .headphoneAudioExposure),
        .init(symbol: "heartRate", displayName: "Heart Rate", identifier: .heartRate),
        .init(symbol: "restingHeartRate", displayName: "Resting Heart Rate", identifier: .restingHeartRate),
        .init(symbol: "walkingHeartRateAverage", displayName: "Walking Heart Rate Average", identifier: .walkingHeartRateAverage),
        .init(symbol: "heartRateVariabilitySDNN", displayName: "Heart Rate Variability SDNN", identifier: .heartRateVariabilitySDNN),
        .init(symbol: "heartRateRecoveryOneMinute", displayName: "Heart Rate Recovery One Minute", identifier: .heartRateRecoveryOneMinute),
        .init(symbol: "atrialFibrillationBurden", displayName: "Atrial Fibrillation Burden", identifier: .atrialFibrillationBurden),
        .init(symbol: "oxygenSaturation", displayName: "Oxygen Saturation", identifier: .oxygenSaturation),
        .init(symbol: "bodyTemperature", displayName: "Body Temperature", identifier: .bodyTemperature),
        .init(symbol: "bloodPressureDiastolic", displayName: "Blood Pressure Diastolic", identifier: .bloodPressureDiastolic),
        .init(symbol: "bloodPressureSystolic", displayName: "Blood Pressure Systolic", identifier: .bloodPressureSystolic),
        .init(symbol: "respiratoryRate", displayName: "Respiratory Rate", identifier: .respiratoryRate),
        .init(symbol: "bloodGlucose", displayName: "Blood Glucose", identifier: .bloodGlucose),
        .init(symbol: "electrodermalActivity", displayName: "Electrodermal Activity", identifier: .electrodermalActivity),
        .init(symbol: "forcedExpiratoryVolume1", displayName: "Forced Expiratory Volume1", identifier: .forcedExpiratoryVolume1),
        .init(symbol: "forcedVitalCapacity", displayName: "Forced Vital Capacity", identifier: .forcedVitalCapacity),
        .init(symbol: "inhalerUsage", displayName: "Inhaler Usage", identifier: .inhalerUsage),
        .init(symbol: "insulinDelivery", displayName: "Insulin Delivery", identifier: .insulinDelivery),
        .init(symbol: "numberOfTimesFallen", displayName: "Number Of Times Fallen", identifier: .numberOfTimesFallen),
        .init(symbol: "peakExpiratoryFlowRate", displayName: "Peak Expiratory Flow Rate", identifier: .peakExpiratoryFlowRate),
        .init(symbol: "peripheralPerfusionIndex", displayName: "Peripheral Perfusion Index", identifier: .peripheralPerfusionIndex),
        .init(symbol: "dietaryBiotin", displayName: "Dietary Biotin", identifier: .dietaryBiotin),
        .init(symbol: "dietaryCaffeine", displayName: "Dietary Caffeine", identifier: .dietaryCaffeine),
        .init(symbol: "dietaryCalcium", displayName: "Dietary Calcium", identifier: .dietaryCalcium),
        .init(symbol: "dietaryCarbohydrates", displayName: "Dietary Carbohydrates", identifier: .dietaryCarbohydrates),
        .init(symbol: "dietaryChloride", displayName: "Dietary Chloride", identifier: .dietaryChloride),
        .init(symbol: "dietaryCholesterol", displayName: "Dietary Cholesterol", identifier: .dietaryCholesterol),
        .init(symbol: "dietaryChromium", displayName: "Dietary Chromium", identifier: .dietaryChromium),
        .init(symbol: "dietaryCopper", displayName: "Dietary Copper", identifier: .dietaryCopper),
        .init(symbol: "dietaryEnergyConsumed", displayName: "Dietary Energy Consumed", identifier: .dietaryEnergyConsumed),
        .init(symbol: "dietaryFatMonounsaturated", displayName: "Dietary Fat Monounsaturated", identifier: .dietaryFatMonounsaturated),
        .init(symbol: "dietaryFatPolyunsaturated", displayName: "Dietary Fat Polyunsaturated", identifier: .dietaryFatPolyunsaturated),
        .init(symbol: "dietaryFatSaturated", displayName: "Dietary Fat Saturated", identifier: .dietaryFatSaturated),
        .init(symbol: "dietaryFatTotal", displayName: "Dietary Fat Total", identifier: .dietaryFatTotal),
        .init(symbol: "dietaryFiber", displayName: "Dietary Fiber", identifier: .dietaryFiber),
        .init(symbol: "dietaryFolate", displayName: "Dietary Folate", identifier: .dietaryFolate),
        .init(symbol: "dietaryIodine", displayName: "Dietary Iodine", identifier: .dietaryIodine),
        .init(symbol: "dietaryIron", displayName: "Dietary Iron", identifier: .dietaryIron),
        .init(symbol: "dietaryMagnesium", displayName: "Dietary Magnesium", identifier: .dietaryMagnesium),
        .init(symbol: "dietaryManganese", displayName: "Dietary Manganese", identifier: .dietaryManganese),
        .init(symbol: "dietaryMolybdenum", displayName: "Dietary Molybdenum", identifier: .dietaryMolybdenum),
        .init(symbol: "dietaryNiacin", displayName: "Dietary Niacin", identifier: .dietaryNiacin),
        .init(symbol: "dietaryPantothenicAcid", displayName: "Dietary Pantothenic Acid", identifier: .dietaryPantothenicAcid),
        .init(symbol: "dietaryPhosphorus", displayName: "Dietary Phosphorus", identifier: .dietaryPhosphorus),
        .init(symbol: "dietaryPotassium", displayName: "Dietary Potassium", identifier: .dietaryPotassium),
        .init(symbol: "dietaryProtein", displayName: "Dietary Protein", identifier: .dietaryProtein),
        .init(symbol: "dietaryRiboflavin", displayName: "Dietary Riboflavin", identifier: .dietaryRiboflavin),
        .init(symbol: "dietarySelenium", displayName: "Dietary Selenium", identifier: .dietarySelenium),
        .init(symbol: "dietarySodium", displayName: "Dietary Sodium", identifier: .dietarySodium),
        .init(symbol: "dietarySugar", displayName: "Dietary Sugar", identifier: .dietarySugar),
        .init(symbol: "dietaryThiamin", displayName: "Dietary Thiamin", identifier: .dietaryThiamin),
        .init(symbol: "dietaryVitaminA", displayName: "Dietary Vitamin A", identifier: .dietaryVitaminA),
        .init(symbol: "dietaryVitaminB12", displayName: "Dietary Vitamin B12", identifier: .dietaryVitaminB12),
        .init(symbol: "dietaryVitaminB6", displayName: "Dietary Vitamin B6", identifier: .dietaryVitaminB6),
        .init(symbol: "dietaryVitaminC", displayName: "Dietary Vitamin C", identifier: .dietaryVitaminC),
        .init(symbol: "dietaryVitaminD", displayName: "Dietary Vitamin D", identifier: .dietaryVitaminD),
        .init(symbol: "dietaryVitaminE", displayName: "Dietary Vitamin E", identifier: .dietaryVitaminE),
        .init(symbol: "dietaryVitaminK", displayName: "Dietary Vitamin K", identifier: .dietaryVitaminK),
        .init(symbol: "dietaryWater", displayName: "Dietary Water", identifier: .dietaryWater),
        .init(symbol: "dietaryZinc", displayName: "Dietary Zinc", identifier: .dietaryZinc),
        .init(symbol: "bloodAlcoholContent", displayName: "Blood Alcohol Content", identifier: .bloodAlcoholContent),
        .init(symbol: "numberOfAlcoholicBeverages", displayName: "Number Of Alcoholic Beverages", identifier: .numberOfAlcoholicBeverages),
        .init(symbol: "appleWalkingSteadiness", displayName: "Apple Walking Steadiness", identifier: .appleWalkingSteadiness),
        .init(symbol: "sixMinuteWalkTestDistance", displayName: "Six Minute Walk Test Distance", identifier: .sixMinuteWalkTestDistance),
        .init(symbol: "walkingSpeed", displayName: "Walking Speed", identifier: .walkingSpeed),
        .init(symbol: "walkingStepLength", displayName: "Walking Step Length", identifier: .walkingStepLength),
        .init(symbol: "walkingAsymmetryPercentage", displayName: "Walking Asymmetry Percentage", identifier: .walkingAsymmetryPercentage),
        .init(symbol: "walkingDoubleSupportPercentage", displayName: "Walking Double Support Percentage", identifier: .walkingDoubleSupportPercentage),
        .init(symbol: "stairAscentSpeed", displayName: "Stair Ascent Speed", identifier: .stairAscentSpeed),
        .init(symbol: "stairDescentSpeed", displayName: "Stair Descent Speed", identifier: .stairDescentSpeed),
        .init(symbol: "timeInDaylight", displayName: "Time In Daylight", identifier: .timeInDaylight),
        .init(symbol: "uvExposure", displayName: "UV Exposure", identifier: .uvExposure),
        .init(symbol: "underwaterDepth", displayName: "Underwater Depth", identifier: .underwaterDepth),
        .init(symbol: "waterTemperature", displayName: "Water Temperature", identifier: .waterTemperature),
        .init(symbol: "appleSleepingBreathingDisturbances", displayName: "Apple Sleeping Breathing Disturbances", identifier: .appleSleepingBreathingDisturbances),
        ]

        return output
    }

    static var categoryEntries: [GeneratedHealthKitCatalogEntry<HKCategoryTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKCategoryTypeIdentifier>] = [
        .init(symbol: "appleStandHour", displayName: "Apple Stand Hour", identifier: .appleStandHour),
        .init(symbol: "lowCardioFitnessEvent", displayName: "Low Cardio Fitness Event", identifier: .lowCardioFitnessEvent),
        .init(symbol: "menstrualFlow", displayName: "Menstrual Flow", identifier: .menstrualFlow),
        .init(symbol: "intermenstrualBleeding", displayName: "Intermenstrual Bleeding", identifier: .intermenstrualBleeding),
        .init(symbol: "infrequentMenstrualCycles", displayName: "Infrequent Menstrual Cycles", identifier: .infrequentMenstrualCycles),
        .init(symbol: "irregularMenstrualCycles", displayName: "Irregular Menstrual Cycles", identifier: .irregularMenstrualCycles),
        .init(symbol: "persistentIntermenstrualBleeding", displayName: "Persistent Intermenstrual Bleeding", identifier: .persistentIntermenstrualBleeding),
        .init(symbol: "prolongedMenstrualPeriods", displayName: "Prolonged Menstrual Periods", identifier: .prolongedMenstrualPeriods),
        .init(symbol: "cervicalMucusQuality", displayName: "Cervical Mucus Quality", identifier: .cervicalMucusQuality),
        .init(symbol: "ovulationTestResult", displayName: "Ovulation Test Result", identifier: .ovulationTestResult),
        .init(symbol: "progesteroneTestResult", displayName: "Progesterone Test Result", identifier: .progesteroneTestResult),
        .init(symbol: "sexualActivity", displayName: "Sexual Activity", identifier: .sexualActivity),
        .init(symbol: "contraceptive", displayName: "Contraceptive", identifier: .contraceptive),
        .init(symbol: "pregnancy", displayName: "Pregnancy", identifier: .pregnancy),
        .init(symbol: "pregnancyTestResult", displayName: "Pregnancy Test Result", identifier: .pregnancyTestResult),
        .init(symbol: "lactation", displayName: "Lactation", identifier: .lactation),
        .init(symbol: "environmentalAudioExposureEvent", displayName: "Environmental Audio Exposure Event", identifier: .environmentalAudioExposureEvent),
        .init(symbol: "headphoneAudioExposureEvent", displayName: "Headphone Audio Exposure Event", identifier: .headphoneAudioExposureEvent),
        .init(symbol: "audioExposureEvent", displayName: "Audio Exposure Event", identifier: .audioExposureEvent),
        .init(symbol: "lowHeartRateEvent", displayName: "Low Heart Rate Event", identifier: .lowHeartRateEvent),
        .init(symbol: "highHeartRateEvent", displayName: "High Heart Rate Event", identifier: .highHeartRateEvent),
        .init(symbol: "irregularHeartRhythmEvent", displayName: "Irregular Heart Rhythm Event", identifier: .irregularHeartRhythmEvent),
        .init(symbol: "appleWalkingSteadinessEvent", displayName: "Apple Walking Steadiness Event", identifier: .appleWalkingSteadinessEvent),
        .init(symbol: "mindfulSession", displayName: "Mindful Session", identifier: .mindfulSession),
        .init(symbol: "sleepAnalysis", displayName: "Sleep Analysis", identifier: .sleepAnalysis),
        .init(symbol: "toothbrushingEvent", displayName: "Toothbrushing Event", identifier: .toothbrushingEvent),
        .init(symbol: "handwashingEvent", displayName: "Handwashing Event", identifier: .handwashingEvent),
        .init(symbol: "abdominalCramps", displayName: "Abdominal Cramps", identifier: .abdominalCramps),
        .init(symbol: "bloating", displayName: "Bloating", identifier: .bloating),
        .init(symbol: "constipation", displayName: "Constipation", identifier: .constipation),
        .init(symbol: "diarrhea", displayName: "Diarrhea", identifier: .diarrhea),
        .init(symbol: "heartburn", displayName: "Heartburn", identifier: .heartburn),
        .init(symbol: "nausea", displayName: "Nausea", identifier: .nausea),
        .init(symbol: "vomiting", displayName: "Vomiting", identifier: .vomiting),
        .init(symbol: "appetiteChanges", displayName: "Appetite Changes", identifier: .appetiteChanges),
        .init(symbol: "chills", displayName: "Chills", identifier: .chills),
        .init(symbol: "dizziness", displayName: "Dizziness", identifier: .dizziness),
        .init(symbol: "fainting", displayName: "Fainting", identifier: .fainting),
        .init(symbol: "fatigue", displayName: "Fatigue", identifier: .fatigue),
        .init(symbol: "fever", displayName: "Fever", identifier: .fever),
        .init(symbol: "generalizedBodyAche", displayName: "Generalized Body Ache", identifier: .generalizedBodyAche),
        .init(symbol: "hotFlashes", displayName: "Hot Flashes", identifier: .hotFlashes),
        .init(symbol: "chestTightnessOrPain", displayName: "Chest Tightness Or Pain", identifier: .chestTightnessOrPain),
        .init(symbol: "coughing", displayName: "Coughing", identifier: .coughing),
        .init(symbol: "rapidPoundingOrFlutteringHeartbeat", displayName: "Rapid Pounding Or Fluttering Heartbeat", identifier: .rapidPoundingOrFlutteringHeartbeat),
        .init(symbol: "shortnessOfBreath", displayName: "Shortness Of Breath", identifier: .shortnessOfBreath),
        .init(symbol: "skippedHeartbeat", displayName: "Skipped Heartbeat", identifier: .skippedHeartbeat),
        .init(symbol: "wheezing", displayName: "Wheezing", identifier: .wheezing),
        .init(symbol: "lowerBackPain", displayName: "Lower Back Pain", identifier: .lowerBackPain),
        .init(symbol: "headache", displayName: "Headache", identifier: .headache),
        .init(symbol: "memoryLapse", displayName: "Memory Lapse", identifier: .memoryLapse),
        .init(symbol: "moodChanges", displayName: "Mood Changes", identifier: .moodChanges),
        .init(symbol: "lossOfSmell", displayName: "Loss Of Smell", identifier: .lossOfSmell),
        .init(symbol: "lossOfTaste", displayName: "Loss Of Taste", identifier: .lossOfTaste),
        .init(symbol: "runnyNose", displayName: "Runny Nose", identifier: .runnyNose),
        .init(symbol: "soreThroat", displayName: "Sore Throat", identifier: .soreThroat),
        .init(symbol: "sinusCongestion", displayName: "Sinus Congestion", identifier: .sinusCongestion),
        .init(symbol: "breastPain", displayName: "Breast Pain", identifier: .breastPain),
        .init(symbol: "pelvicPain", displayName: "Pelvic Pain", identifier: .pelvicPain),
        .init(symbol: "vaginalDryness", displayName: "Vaginal Dryness", identifier: .vaginalDryness),
        .init(symbol: "acne", displayName: "Acne", identifier: .acne),
        .init(symbol: "drySkin", displayName: "Dry Skin", identifier: .drySkin),
        .init(symbol: "hairLoss", displayName: "Hair Loss", identifier: .hairLoss),
        .init(symbol: "nightSweats", displayName: "Night Sweats", identifier: .nightSweats),
        .init(symbol: "sleepChanges", displayName: "Sleep Changes", identifier: .sleepChanges),
        .init(symbol: "bladderIncontinence", displayName: "Bladder Incontinence", identifier: .bladderIncontinence),
        ]

        if #available(iOS 26.2, *) {
            output.append(.init(symbol: "hypertensionEvent", displayName: "Hypertension Event", identifier: .hypertensionEvent))
        }

        return output
    }

    static var characteristicEntries: [GeneratedHealthKitCatalogEntry<HKCharacteristicTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKCharacteristicTypeIdentifier>] = [
        .init(symbol: "activityMoveMode", displayName: "Activity Move Mode", identifier: .activityMoveMode),
        .init(symbol: "biologicalSex", displayName: "Biological Sex", identifier: .biologicalSex),
        .init(symbol: "bloodType", displayName: "Blood Type", identifier: .bloodType),
        .init(symbol: "dateOfBirth", displayName: "Date Of Birth", identifier: .dateOfBirth),
        .init(symbol: "fitzpatrickSkinType", displayName: "Fitzpatrick Skin Type", identifier: .fitzpatrickSkinType),
        .init(symbol: "wheelchairUse", displayName: "Wheelchair Use", identifier: .wheelchairUse),
        ]

        return output
    }

    static var correlationEntries: [GeneratedHealthKitCatalogEntry<HKCorrelationTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKCorrelationTypeIdentifier>] = [
        .init(symbol: "bloodPressure", displayName: "Blood Pressure", identifier: .bloodPressure),
        .init(symbol: "food", displayName: "Food", identifier: .food),
        ]

        return output
    }

    static var clinicalEntries: [GeneratedHealthKitCatalogEntry<HKClinicalTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKClinicalTypeIdentifier>] = [
        .init(symbol: "allergyRecord", displayName: "Allergy Record", identifier: .allergyRecord),
        .init(symbol: "clinicalNoteRecord", displayName: "Clinical Note Record", identifier: .clinicalNoteRecord),
        .init(symbol: "conditionRecord", displayName: "Condition Record", identifier: .conditionRecord),
        .init(symbol: "immunizationRecord", displayName: "Immunization Record", identifier: .immunizationRecord),
        .init(symbol: "labResultRecord", displayName: "Lab Result Record", identifier: .labResultRecord),
        .init(symbol: "medicationRecord", displayName: "Medication Record", identifier: .medicationRecord),
        .init(symbol: "procedureRecord", displayName: "Procedure Record", identifier: .procedureRecord),
        .init(symbol: "vitalSignRecord", displayName: "Vital Sign Record", identifier: .vitalSignRecord),
        .init(symbol: "coverageRecord", displayName: "Coverage Record", identifier: .coverageRecord),
        ]

        return output
    }

    static var documentEntries: [GeneratedHealthKitCatalogEntry<HKDocumentTypeIdentifier>] {
        var output: [GeneratedHealthKitCatalogEntry<HKDocumentTypeIdentifier>] = [
        .init(symbol: "CDA", displayName: "CDA", identifier: .CDA),
        ]

        return output
    }

}
